// <auto-generated />
using CarLove.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace CarLove.Migrations
{
    [DbContext(typeof(MapleContext))]
    partial class MapleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("CarLove.Models.Lot", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CurrentCount");

                    b.Property<string>("Location");

                    b.Property<string>("Lotname");

                    b.Property<int>("Maxsize");

                    b.Property<string>("Src");

                    b.Property<int?>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Lots");
                });

            modelBuilder.Entity("CarLove.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CarLove.Models.Lot", b =>
                {
                    b.HasOne("CarLove.Models.User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
